# This needs to be a separate workflow for PRs from forked repos to be reported properly,
# see https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories
name: Generate test reports
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v2
      with:
        artifact: test-\w+-[0-9.]+@\w+-[\w.]+
        name: Unit tests
        path: 'test-*.xml'
        reporter: jest-junit
